version: "3.8"

services:
  browserless:
    image: browserless/chrome:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - puppeteer-net
    # Exposing port 3000 for internal and external access (scraper to use it)
    ports:
      - "3000:3000"  # Browserless service port

  scraper:
    build:
      context: .
      dockerfile: puppeteer-service/Dockerfile
    image: ghcr.io/archiscript/puppeteer-scraper:latest
    networks:
      - puppeteer-net
    environment:
      - WS_ENDPOINT=ws://browserless:3000   # WebSocket connection to browserless
      - WEBHOOK_SECRET_FILE=/run/secrets/webhook_secret
    secrets:
      - WEBHOOK_SECRET
      - deploy_key
    # Exposing port 8080 for webhook access
    ports:
      - target: 8080          # port *inside* the container
        published: 8080       # port exposed on the host
        protocol: tcp
        mode: host 
        
    healthcheck:
      test: ["CMD", "curl", "-f", "http://browserless:3000"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  puppeteer-net:
    external: true  # Using an external network for inter-service communication

secrets:
  WEBHOOK_SECRET:
    external: true  # Assumes this secret is already created in Portainer or Docker Swarm
  deploy_key:
    external: true  
