name: Pull Latest and Trigger Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'puppeteer-service/**' # Ignore Docker-related files

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy Webhook
        run: |
          curl -X POST https://your-server.com:9000/hooks/scraper-deploy \
            -H "X-Hub-Signature: ${{ secrets.WEBHOOK_SECRET }}"
