name: Pull Latest and Trigger Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'puppeteer-service/**' 

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy Webhook
        run: |
          response=$(curl -s -w "\n%{http_code}" -X GET https://9eb7fcd6c642.ngrok-free.app/test \
            -H "X-Hub-Signature: ${{ secrets.WEBHOOK_SECRET }}")
          body=$(echo "$response" | sed '$d')
          status=$(echo "$response" | tail -n1)

          echo "Status: $status"
          echo "Body: $body"

          [ "$status" -eq 200 ]
